### ISSUE TITLE
Latest version is 0.17, but pypi is at 0.18.1

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/mkdocstrings-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The latest available version of mkdocstrings from conda-forge is currently 0.17, but the latest version available from pypi is now at 0.18.1

```
 conda search -c conda-forge 'mkdocstrings >=0.17'
Loading channels: done
# Name                       Version           Build  Channel             
mkdocstrings                  0.17.0    pyhd8ed1ab_0  conda-forge        
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h033912b_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
python                    3.8.12          h43ca1e7_3_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                60.9.3           py38h50d1736_0    conda-forge
sqlite                    3.37.0               h23a322b_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
```

### Environment info

```shell
active environment : tmp
    active env location : /Users/cbarber/miniconda3/envs/tmp
            shell level : 3
       user config file : /Users/cbarber/.condarc
 populated config files : /Users/cbarber/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.7.3.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/cbarber/miniconda3  (writable)
      conda av data dir : /Users/cbarber/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/cbarber/miniconda3/pkgs
                          /Users/cbarber/.conda/pkgs
       envs directories : /Users/cbarber/miniconda3/envs
                          /Users/cbarber/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.24.0 CPython/3.7.3 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by bandersen23** [comment]
Thanks @analog-cbarber! I have an idea of how to fix this. It requires a couple of builds, but I'll document it below as I work on them:

- [x] 1. Patch `0.18.0` to remove python-legacy handler as that isn't in `conda-forge` yet via #20 
- [x] 2. Get handlers into `conda-forge` via conda-forge/staged-recipes#18245 - _waiting_ on conda-forge/staged-recipes#18287
- [x] 3. Create new build of `0.18.0` to now include the handler by default via #24 
- [x] 4. Add `0.18.1` via #25

**Comment by hadim** [comment]
Thanks @bandersen23 .

To be able to merge https://github.com/conda-forge/staged-recipes/pull/17960, we first need https://github.com/mkdocstrings/mkdocstrings/issues/376 to be adressed.

**Comment by bandersen23** [comment]
This would be a way around it. We could build 0.18.0 without the legacy handler. Then build the legacy handler. Then rebuild 0.18.0 to include the legacy handler. Does that make sense? The legacy handler isn't imported in mkdocstrings, just installed, so this would be a way to build both. 

Once we rebuild 0.18.0 with the legacy handler, that would get installed over the one without.

**Comment by hadim** [comment]
It seems like the new feedstock repos are empty: https://github.com/conda-forge/staged-recipes/pull/18245#issuecomment-1061724777

**Comment by bandersen23** [comment]
This is waiting on conda-forge/staged-recipes#18287
